name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch 
      uses: actions/checkout@v2
    - name: Docker Login
      run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: |
        cd AuthenticationService
        docker build -t saenthan/authenticationservice:latest .
    - name: Push to Docker Hub
      run: |
        docker push ${{secrets.DOCKER_USERNAME}}/authenticationservice
