name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch 
      uses: actions/checkout@v2
    - name: Docker Login
      run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: |
        cd AuthenticationService
        docker build -t saenthan/authenticationservice:latest .
        cd ..
        cd EmailService
        docker build -t saenthan/emailservice:latest .
        cd ..
        cd PersonalNetworkService
        docker build -t saenthan/personalnetworkservice:latest .
        cd ..
        cd PostService
        docker build -t saenthan/postservice:latest .
        cd ..
        cd FeedService
        docker build -t saenthan/feedservice:latest .
    - name: Push to Docker Hub
      run: |
        docker push ${{secrets.DOCKER_USERNAME}}/authenticationservice
        docker push ${{secrets.DOCKER_USERNAME}}/emailservice
        docker push ${{secrets.DOCKER_USERNAME}}/personalnetworkservice
        docker push ${{secrets.DOCKER_USERNAME}}/postservice
        docker push ${{secrets.DOCKER_USERNAME}}/feedservice
